server:
  port: 8978

clients:
  sonarr:
    url: "http://localhost:8989"
    api-key: "4ed7f4d0e8584d65ab9d47d944077ff3"
  radarr:
    url: "http://localhost:7878"
    api-key: "cd0912f129d344g9b69bb20d49fcbe49"
  torrent:
    type: QBITTORRENT
    name: qBittorrent
    url: "http://localhost:8080"
    username: admin
    password: adminadmin
